## 제어문과 반복문

In [1]:
#while 조건문에는 C처럼 숫자가 올 수도 있다. (T/F)

## 함수

In [2]:
def f(x):
    return x + 10
f(10)

20

In [3]:
lambda x: x+10(10) #람다

<function __main__.<lambda>>

## Numpy

In [4]:
#일반 파이썬 list로 다차원배열 생성

data = [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]
flotV = [data, data, data]

flotV

[[1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [5]:
flotV[0]

[1.0, 10.4, 3.2, 5.1, 7.5, 2.7]

In [6]:
flotV[0] = "Python"

flotV

['Python', [1.0, 10.4, 3.2, 5.1, 7.5, 2.7], [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [7]:
import numpy as np

a = np.array([1, 2.5, 4.0, 5.5, 7.0])

a[3:] #ndarray가 list보다 빠르다.

array([ 5.5,  7. ])

In [8]:
print(a.sum()) #합계
print(a.std()) #표준편차
print(a.cumsum()) #누적합

20.0
2.12132034356
[  1.    3.5   7.5  13.   20. ]


In [9]:
print(a*2) #곱하기 2 #파이썬의 list와 다르다. 주의
print(a**2) #제곱
print(np.sqrt(a)) #제곱근

[  2.   5.   8.  11.  14.]
[  1.     6.25  16.    30.25  49.  ]
[ 1.          1.58113883  2.          2.34520788  2.64575131]


In [10]:
b = np.array([a, a**2])
b

array([[  1.  ,   2.5 ,   4.  ,   5.5 ,   7.  ],
       [  1.  ,   6.25,  16.  ,  30.25,  49.  ]])

In [11]:
b.sum(axis=0) #축(axis)가 0일 경우 세로 축의 합 출력

array([  2.  ,   8.75,  20.  ,  35.75,  56.  ])

In [12]:
b.sum(axis=1) #가로 축의 합

array([  20. ,  102.5])

In [13]:
np.zeros((2, 3), dtype="I") #I: 정수형, f:소수형. #np.array([[0, 0, 0], [0, 0, 0]])와 같다

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint32)

## Pandas

In [14]:
import pandas as pd

#Series는 컬럼이 한 개인 경우 - 1차원. Value와 index로 되어 있다.
pd_series = pd.Series([3000, 3200, 2700], index=["2016-11-10", "2016-11-11", "2016-11-12"]) #value와 index

pd_series

2016-11-10    3000
2016-11-11    3200
2016-11-12    2700
dtype: int64

In [15]:
pd_series[1:] #slicing

2016-11-11    3200
2016-11-12    2700
dtype: int64

In [16]:
#DataFrame은 컬럼이 다수인 경우

df = pd.DataFrame([100, 150, 200, 250, 300], columns=["numbers"], index=["a", "b", "c", "d", "e"])

df

numbers
a      100
b      150
c      200
d      250
e      300

In [17]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [18]:
df.columns

Index(['numbers'], dtype='object')

In [19]:
df.ix["c"] #인덱스로 값 추출

numbers    200
Name: c, dtype: int64